
services:  
    web:    
      build:
        ./flask-app    
      ports:     
        - "5000:5000"    
      networks:     
        - app-network    
      volumes:      
        - flask-data:/app/data  
    mongo:    
      image: mongo    
      restart: always    
      ports:      
        - "27017:27017"    
      networks:      
        - app-network    
      volumes:      
        - mongo-data:/data/db
networks:  
    app-network:    
        driver: bridge
volumes:  
    flask-data:  
    mongo-data:
